In [1]:
import pandas as pd
import numpy as np

In [34]:
dataframe = pd.read_csv("googleplaystore.csv")
data = dataframe

In [35]:
data = data.dropna()

In [36]:
data.shape

(9360, 13)

In [37]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9360 entries, 0 to 10839
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9360 non-null   object
 1   Category        9360 non-null   object
 2   Rating          9360 non-null   float64
 3   Reviews         9360 non-null   int64
 4   Size            9360 non-null   object
 5   Installs        9360 non-null   object
 6   Type            9360 non-null   object
 7   Price           9360 non-null   object
 8   Content Rating  9360 non-null   object
 9   Genres          9360 non-null   object
 10  Last Updated    9360 non-null   object
 11  Current Ver     9360 non-null   object
 12  Android Ver     9360 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 1023.8+ KB

In [39]:
res = data['Installs']

In [40]:
f=res.apply(lambda x:x.replace("+",""))
f

0            10,000
1           500,000
2         5,000,000
3        50,000,000
4           100,000
            ...
10833           500
10835         5,000
10836           100
10838         1,000
10839    10,000,000
Name: Installs, Length: 9360, dtype: object

In [44]:
data['Size'].apply(lambda x:x.replace("M",""))

0                        19
1                        14
2                       8.7
3                        25
4                       2.8
                ...
10833                   2.6
10835                    53
10836                   3.6
10838    Varies with device
10839                    19
Name: Size, Length: 9360, dtype: object

In [50]:
pd.to_numeric(data['Size'], errors='coerce')
data.groupby(['Category']).mean()

                       Rating       Reviews       Size
Category
ART_AND_DESIGN       4.377049  2.810356e+04  12.939655
AUTO_AND_VEHICLES    4.190411  1.594014e+04  21.885484
BEAUTY               4.278571  9.407929e+03  15.513514
BOOKS_AND_REFERENCE  4.346067  1.233633e+05  14.682979
BUSINESS             4.121452  4.605309e+04  15.401261
COMICS               4.155172  5.830940e+04  13.695745
COMMUNICATION        4.158537  2.486164e+06  14.077957
DATING               3.970769  3.738994e+04  18.312717
EDUCATION            4.389032  2.554517e+05  21.136111
ENTERTAINMENT        4.126174  3.971688e+05  21.853333
EVENTS               4.435556  3.568667e+03  14.813514
FAMILY               4.192383  2.349501e+05  30.571706
FINANCE              4.131889  5.433562e+04  19.009231
FOOD_AND_DRINK       4.166972  8.149550e+04  24.163095
GAME                 4.286326  1.445232e+06  45.479197
HEALTH_AND_FITNESS   4.277104  1.275880e+05  24.562727
HOUSE_AND_HOME       4.197368  5.231584e+04  17.505357
LIBRARIES_AND_DEMO   4.179688  1.583422e+04  22.405882
LIFESTYLE            4.094904  4.102474e+04  15.809559
MAPS_AND_NAVIGATION  4.051613  2.472505e+05  17.815054
MEDICAL              4.189143  4.530349e+03  20.260000
NEWS_AND_MAGAZINES   4.132189  2.334760e+05  13.283234
PARENTING            4.300000  1.907218e+04  21.579545
PERSONALIZATION      4.335256  2.863634e+05  12.729134
PHOTOGRAPHY          4.192114  6.735540e+05  17.748291
PRODUCTIVITY         4.211396  3.251189e+05  13.877523
SHOPPING             4.259664  4.833657e+05  17.688439
SOCIAL               4.255598  2.398614e+06  19.384000
SPORTS               4.223511  2.220363e+05  26.610976
TOOLS                4.047203  3.726878e+05   9.277265
TRAVEL_AND_LOCAL     4.109292  2.770698e+05  25.403774
VIDEO_PLAYERS        4.063750  6.898731e+05  16.734821
WEATHER              4.244000  1.947293e+05  13.662000

In [47]:
pd.to_numeric(data['Size'], errors='coerce')

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10833     2.6
10835    53.0
10836     3.6
10838     NaN
10839    19.0
Name: Size, Length: 9360, dtype: float64